[programs.localnet]
wtia_auction = "7HB9xKFZ2fNE3E4BJN3fjZF2X7Piwt8owRi8L2LTpj23"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/dunnis/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
